spring:
  profiles:
    active: dev   #环境设置 dev，开发环境
  datasource:
    druid:
      driver-class-name: ${mysky.datasource.driver-class-name}
      url: ${mysky.datasource.url}
      username: ${mysky.datasource.username}
      password: ${mysky.datasource.password}
  redis:
    host: ${mysky.redis.host}
    port: ${mysky.redis.port}
    database: ${mysky.redis.database}
    password: ${mysky.redis.password}

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fzdkx.entity
  configuration:
    map-underscore-to-camel-case: true    #开启驼峰命名映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #sql日志

sky:
  jwt:
    secure-key: dihdiosahdskandioadhuisadhd
    ttl: 2
    admin-token-name: token
    user-token-name: authentication
  oos:
    endpoint: ${mysky.oos.endpoint}
    access-key-id: ${mysky.oos.access-key-id}
    access-key-secret: ${mysky.oos.access-key-secret}
    bucket-name: ${mysky.oos.bucket-name}
  wechat:
    appid: ${mysky.wx.appid}
    secret: ${mysky.wx.secret}
#    mchid: ${mysky.wx.mchid}
#    mchSerialNo: ${mysky.wx.mchSerialNo}
#    privateKeyFilePath: ${mysky.wx.privateKeyFilePath}
#    apiV3Key: ${mysky.wx.apiV3Key}
#    weChatPayCertFilePath: ${mysky.wx.weChatPayCertFilePath}
#    notifyUrl: ${mysky.wx.notifyUrl}
#    refundNotifyUrl: ${mysky.wx.refundNotifyUrl}
  baidu:
    ak: ${mysky.baidu.ak}
    shop-address: ${mysky.baidu.shop-address}
