spring:
  profiles:
    active: dev   #环境设置 dev，开发环境
  datasource:
    druid:
      driver-class-name: ${sky.datasource.driver-class-name}
      url: ${sky.datasource.url}
      username: ${sky.datasource.username}
      password: ${sky.datasource.password}
  redis:
    host: ${sky.redis.host}
    port: ${sky.redis.port}
    database: ${sky.redis.database}
    password: ${sky.redis.password}

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fzdkx.entity
  configuration:
    map-underscore-to-camel-case: true    #开启驼峰命名映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #sql日志

sky:
  jwt:
    secure-key: dihdiosahdskandioadhuisadhd
    ttl: 2
    token-name: token
  oos:
    endpoint: ${sky.oos.endpoint}
    access-key-id: ${sky.oos.access-key-id}
    access-key-secret: ${sky.oos.access-key-secret}
    bucket-name: ${sky.oos.bucket-name}