sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sky_takeout?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: abc123
  redis:
    host: 192.168.3.166
    port: 6379
    database: 1
    password: 123321
  oos:
    endpoint: oss-cn-heyuan.aliyuncs.com
    access-key-id: LTAI5tB3NTWMoKZcXmdLXXBq
    access-key-secret: s7m09hFzGIJsfAMmRaCOJMGxhUy6R6
    bucket-name: fzdkx-sky
  wx:
    appid: wx2930ad0234941e54
    secret: 1e5ccf37b6cd406f96222660fe390eaf
